name: Scaffolding
description: "Where does the description show?"
inputs:
  command:
    description: "Is the input description used anywhere?"
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}
