name: Android

on: [push, pull_request]

jobs:
  Android_Build:
    name: Android (Build)
    runs-on: ubuntu-20.04
    container: swift:5.7.3-focal
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: |
        set -x
        swift run --package-path Scaffolding scaffolding prepare‐kotlin
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Kotlin
        path: .Construction/Kotlin
    - name: Check repository for changes
      shell: bash
      run: |
        set -x
        git config --global --add safe.directory '*'
        git add . --intent-to-add
        git diff --exit-code
  Android_Test:
    name: Android (Test)
    runs-on: ubuntu-20.04
    #needs: Android_Build
    steps:
    - name: Check out
      uses: actions/checkout@v2
    #- name: Download
    #  uses: actions/download-artifact@v4
    #  with:
    #    name: Kotlin
    #    path: .Construction/Kotlin
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.10"
    - name: Prepare tests
      shell: bash
      run: |
        set -x
        cd Construction/Kotlin
        gradle wrapper
        ./gradlew tasks
        #./gradlew sourceSets
        ./gradlew build
        ./gradlew assembleAndroidTest
        ./gradlew test
        ./gradlew check
    - name: Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        #arch: x86_64
        #disable-animations: true
        #disk-size: 6000M
        #heap-size: 600M
        script: ./gradlew connectedDebugAndroidTest
