name: Proofread

on: [push, pull_request]

jobs:
  Proofread:
    name: Proofread
    runs-on: ubuntu-20.04
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Format
      uses: ./.github/actions/Scaffolding
      with:
        run: |
          set -x
          swift run --package-path Scaffolding scaffolding format
          swift run --package-path Scaffolding scaffolding rescaffold
    - name: Check repository for changes
      shell: bash
      run: |
        set -x
        git config --global --add safe.directory '*'
        git add . --intent-to-add
        git diff --exit-code
