name: Windows

on: [push, pull_request]

jobs:
  Windows_Build:
    name: Windows (Build)
    runs-on: ubuntu-24.04
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/Scaffolding
      with:
        run: |
          set -x
          swift run --package-path Scaffolding scaffolding prepare‐c‐sharp
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: C♯
        path: .Construction/C♯
    - name: Check repository for changes
      shell: bash
      run: |
        set -x
        git config --global --add safe.directory '*'
        git add . --intent-to-add
        git diff --exit-code
  Windows_Test:
    name: Windows (Test)
    runs-on: windows-2022
    needs: Windows_Build
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: C♯
        path: .Construction/C♯
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17.14,17.15)'
    - name: Build All
      shell: cmd
      run: |
        echo on
        msbuild .Construction\C♯\Project.csproj -target:Build -restore
    - name: Test with .NET Framework
      shell: cmd
      run: |
        echo on
        .Construction\C♯\bin\Debug\net48\win-x86\Project.exe
    - name: Test with .NET
      shell: cmd
      run: |
        echo on
        .Construction\C♯\bin\Debug\netcoreapp3.0\win-x86\Project.exe
